---
- name: Ensure pciutils installed
  yum:
    name: pciutils
    state: present
# only NVIDIA for now
- name: Detect NVIDIA devices
  command: "lspci -d {{ item.vendor|default('') }}:{{ item.device|default('') }}:{{ item.class|default('') }} -nn -mm"
  register: lspci_nvidia
  with_items: "{{ nvidia_device_query }}"
  changed_when: false

- name: Install pip to install python-docker
  yum:
    name: python-pip
    state: present
  register: dcos_yum_pythonpip_install
  retries: 3
  delay: 60
  until: dcos_yum_pythonpip_install is success

- name: Install python jmespath
  pip:
    name:
       - jmespath
    state: present
  register: dcos_pip_jmespath_install
  retries: 3
  delay: 60
  until: dcos_pip_jmespath_install is success

- name: "NVIDIA GPU detected"
  include_tasks: nvidia-gpu.yml
  when: lspci_nvidia|json_query('results[*].stdout_lines')|flatten|length > 0
